name: Basic Action Skills
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a sample script
        run: echo "Hello, Github Actions Workshop Workflow"